boycott/urls.py
from django.conf.urls import url
from django.contrib import admin
import account.views

from django.conf.urls import url

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',account.views.home, name='home'),
    # url(r'^alert/(?P<alert>[0-9]+)',account.views.home, name='home'),
    url(r'', include('account.urls')),
    url(r'', include('boycotted.urls')),
    url(r'', include('polls.urls')),
]

boycotted/urls.py
from django.conf.urls import url
# from . import views
from boycotted.views import *

urlpatterns = [
    url(r'^boycott/add/', AddBoycott, name='AddBoycott'),
    url(r'^boycott/edit/(?P<boycott_id>[0-9]+)', EditBoycott, name='EditBoycott'),
    url(r'^boycotted/edit/(?P<boycotted_id>[0-9]+)', EditBoycotted, name='EditBoycotted'),
    url(r'^boycotted/view/all/', ViewAllBoycotted),
    url(r'^boycotted/view/(?P<boycotted_id>[0-9]+)', ViewBoycotted),
    url(r'^boycotted/incrementComment/(?P<identifier>[A-z0-9-]+)', IncrementComment),
    url(r'^boycott/delete/(?P<boycott_id>[0-9]+)', DeleteBoycott),
    url(r'^boycotted/delete/(?P<boycotted_id>[0-9]+)', DeleteBoycotted)
]

polls/urls.py
from django.conf.urls import url
# from . import views
from polls.views import *

urlpatterns = [
    url(r'^poll/view/all', ViewAllPolls),
    url(r'^poll/view/(?P<poll_id>[0-9]+)', ViewPoll),
    url(r'^poll/vote/$', ViewAllPolls),
    url(r'^poll/vote/(?P<poll_id>[0-9]+)', VotePoll, name='VotePoll'),
    url(r'^poll/delete/(?P<poll_id>[0-9]+)', DeletePoll, name='DeletePoll'),
    url(r'^console/make_poll', MakePoll, name='make_poll'),


    # url(r'^poll/answer/(?P<poll_id>[0-9]+)', polls.views.AnswerPoll)
]

boycotted/models.py
from django.core.validators import RegexValidator
from account.models import *
import datetime

# Create your models here.
TAG_CHOICES = (
    (1, ("Other")),
    (2, ("People")),
    (3, ("Sports")),
    (4, ("Businesses")),
    (5, ("International")),
    (6, ("Local"))
)

FILTER_TAG_CHOICES = (
    (1, ("All")),
    (2, ("Other")),
    (3, ("People")),
    (4, ("Sports")),
    (5, ("Businesses")),
    (6, ("International")),
    (7, ("Local"))
)

SORT_CHOICES = (
    (1, ("Most Boycotted")),
    (2, ("Alphabetical Order")),
    (3, ("Most Recent")),
    (4, ("Most Comments"))
)


# This model describes an entity being boycotted i.e. Trump or My local applebee's
class Boycotted(models.Model):
    # Name of the person/place being boycotted
    name = models.CharField(max_length=500, verbose_name="Entity being boycotted")
    # Location of a local variant of the boycotted or null if it's a non-local thing
    zip = models.CharField(max_length=5,
                           null=True,
                           blank=True,
                           validators=[
                               RegexValidator(r'^\d{1,10}$',
                                              message="Please enter a valid zipcode")
                           ]
                           )
    # The boycotts filed against the boycotted object
    boycotts = models.ManyToManyField("boycotted.Boycott", blank=True)
    date = models.DateTimeField(default=datetime.datetime.now)
    tag = models.IntegerField(default=1, choices=TAG_CHOICES)
    comment_count = models.IntegerField(default=0)

    def __str__(self):
        return 'Boycotted: ' + self.name


# This class represents an individual instance of a boycott. Think Grandma boycotting Obama
class Boycott(models.Model):
    # The user doing the boycotting
    boycotter = models.ForeignKey(
        'account.BoycottUser',
        on_delete=models.CASCADE
    )
    # The time/date the boycott was submitted
    date = models.DateTimeField(default=datetime.datetime.now)
    # The reason for the boycott
    reason = models.CharField(max_length=500, verbose_name="Why are you boycotting?")
    # Target, not sure if needed yet
    target = models.ForeignKey(
        Boycotted,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return 'Target: ' + self.target.name + ' - Boycotter: ' + self.boycotter.username + ' - Reason: ' + self.reason


class DirtyFilterModelIFeelGuiltyAbout(models.Model):
    tag = models.IntegerField(default=0, choices=FILTER_TAG_CHOICES)
    sort = models.IntegerField(default=0, choices=SORT_CHOICES)

boycotted/forms.py
from django import forms
from boycotted.models import Boycott, Boycotted, DirtyFilterModelIFeelGuiltyAbout, SORT_CHOICES


class BoycottedForm(forms.ModelForm):
    class Meta:
        model = Boycotted
        fields = ['name', 'zip', 'tag']
class AdminTagForm(forms.ModelForm):
    class Meta:
        model = Boycotted
        fields = ['tag']


class BoycottForm(forms.ModelForm):
    class Meta:
        model = Boycott
        fields = ['reason']

class FilterForm(forms.ModelForm):
    sort = forms.ChoiceField(choices=SORT_CHOICES, initial='',
                                        widget=forms.RadioSelect)
    class Meta:
        model = DirtyFilterModelIFeelGuiltyAbout
        fields = ['tag']

boycotted/views.py
from datetime import datetime
import requests
from account.views import _get_disqus_sso
from django.contrib.auth.decorators import login_required, user_passes_test
import json
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

from boycott.general import process_zip
from boycott.settings import SERVER
from boycotted.forms import *
from boycotted.models import *
from uszipcode import ZipcodeSearchEngine

# Create your views here.
@login_required(login_url='/login/')
def AddBoycott(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        boycott_form = BoycottForm(data=request.POST)
        boycotted_form = BoycottedForm(data=request.POST)
        boycotted=[]
        if boycotted_form.is_valid() and boycott_form.is_valid():
            # Save boycotted values to access
            temp_boycotted = boycotted_form.save(commit=False)

            # Check to see if boycotted exists already
            boycotted_query = Boycotted.objects.filter(name=temp_boycotted.name).filter(zip=temp_boycotted.zip)
            if boycotted_query.count() > 0:
            #     If the boycotted exists already, fetch it.
                boycotted = boycotted_query[0]
            else:
                # boycotted = boycotted_form.save(commit=False)
                boycotted = boycotted_form.save()
                # boycotted.date = datetime.now()
                # boycotted.save()

            # process data in form
            boycott = boycott_form.save(commit=False)
            boycott.boycotter = request.user
            # boycott.date = datetime.now()
            boycott.target = boycotted
            boycott.save()

            boycotted.boycotts.add(boycott)
            boycotted.save()
            request.user.boycotts.add(boycott)
            return HttpResponseRedirect('/boycotted/view/'+str(boycotted.id))

    else:
        boycott_form = BoycottForm()
        boycotted_form = BoycottedForm()
        boycotted=[]
        for boycott in Boycotted.objects.all():
            boycotted.append(boycott.name)




    return render(request, 'add_boycott.html', {
        'boycott_form': boycott_form,
        'boycotted_form':boycotted_form,
        'boycotted':json.loads(json.dumps(boycotted))
    })


# @login_required(login_url='/login/')
def ViewBoycotted(request,boycotted_id):
    # if this is a POST request we need to process the form data
    boycotts=[]

    boycotted=Boycotted.objects.get(id=boycotted_id)

    if boycotted.zip == "":
        zip=""
        location = ""
    else:
        zip=boycotted.zip
        search = ZipcodeSearchEngine()
        location = search.by_zipcode(zip)
        location = "(" + str(location.City) + ", " + str(location.State) + ")"
    for boycott in boycotted.boycotts.all():
        boy={
            'username':boycott.boycotter.username,
            'date':boycott.date.strftime("%m/%d/%y"),
            'reason':boycott.reason,
            'id':boycott.id
        }
        boycotts.append(boy)
    decoded_json = json.loads(json.dumps(boycotts))


    disqus_sso = _get_disqus_sso(request.user)

    # identifier= SERVER+'-Boycotted-'+boycotted_id
    #
    #
    # IncrementComment(request, identifier)

    return render(request, 'view_boycotted.html', {
        'name': boycotted.name,
        'zip': zip,
        'location': location,
        'boycotts': decoded_json,
        "disqus_sso": disqus_sso,
        'id':boycotted_id
    })


@login_required(login_url='/login/')
def EditBoycott(request,boycott_id):
    prnt=''
    boycott = Boycott.objects.get(id=boycott_id)
    if request.user.username != boycott.boycotter.username:
        return HttpResponseRedirect('/')

    if boycott.target.zip == "":
        zip=""
        location = ""
    else:
        zip=boycott.target.zip
        search = ZipcodeSearchEngine()
        location = search.by_zipcode(zip)
        location = "(" + str(location.City) + ", " + str(location.State) + ")"

    if request.method == 'POST':

        boycott_form = BoycottForm(data=request.POST, instance=boycott)
        tag_form = AdminTagForm(data=request.POST)
        if boycott_form.is_valid() and tag_form.is_valid():

            tag = str(int(tag_form.cleaned_data['tag']))

            target=Boycott.objects.get(id=boycott_id).target

            new_boycott = boycott_form.save(commit=False)

            boycott.reason=new_boycott.reason
            target.tag = int(tag)
            boycott.save()
            target.save()

            return HttpResponseRedirect('/')

    else:
        boycott_form = BoycottForm(instance=boycott)
        tag_form = AdminTagForm(instance=boycott)

    return render(request, 'edit_boycott.html',
                  {'boycott_form': boycott_form,
                   'tag_form':tag_form,
                   'name': boycott.target.name,
                   'location': location,
                   'boycott_id': boycott_id,
                   'prnt':prnt
                   })


@user_passes_test(lambda u: u.is_superuser, login_url='/login/')
def EditBoycotted(request,boycotted_id):

    boycotted = Boycotted.objects.get(id=boycotted_id)

    if boycotted.zip == "":
        zip=""
        location = ""
    else:
        zip=boycotted.zip
        search = ZipcodeSearchEngine()
        location = search.by_zipcode(zip)
        location = "(" + str(location.City) + ", " + str(location.State) + ")"


    if request.method == 'POST':
        print('actuallyposting')
        boycotted_form = BoycottedForm(data=request.POST)

        tag =  boycotted_form.data['tag']
        # new_boycotted = boycotted_form.save(commit=False)

        boycotted.tag = tag
        boycotted.save()
        return HttpResponseRedirect('/boycotted/view/all/')

    else:
        boycotted_form = BoycottedForm(instance=boycotted)

    return render(request, 'edit_boycotted.html',
                  {'boycotted_form': boycotted_form,
                   'name': boycotted.name,
                   'location': location,
                   'boycotted_id': boycotted_id,

                   })


@login_required(login_url='/login/')
def DeleteBoycott(request, boycott_id):
    boycott = Boycott.objects.get(id=boycott_id)
    if not request.user.is_superuser:
        if request.user.username != boycott.boycotter.username:
            return HttpResponseRedirect('/boycotted/view/all/')
    boycotted=boycott.target
    boycott.delete()
    if boycotted.boycotts.count()==0:
        boycotted.delete()


    return HttpResponseRedirect('/')

def ViewAllBoycotted(request):
        all_boycotted = []
        for bct in Boycotted.objects.all():

            pol = {
                'name': bct.name,
                'id': bct.id,
                "location": process_zip(bct.zip)
            }
            all_boycotted.append(pol)

        return render(request, 'view_all_boycotted.html', {
            'all_boycotted': all_boycotted
        })

@user_passes_test(lambda u: u.is_superuser, login_url='/login/')
def DeleteBoycotted(request, boycotted_id):
    boycotted = Boycotted.objects.get(id=boycotted_id)

    boycotted.delete()


    return HttpResponseRedirect('/')

def IncrementComment(request,identifier):

    params=identifier.split('-')
    boycotted= Boycotted.objects.get(id=params[2])

    params={
        "api_key":"UCkYzgSPnP4OtgopaqnhrhMrQnL6a8hJBvfzslmbB80N1jCaTexRI7mmVBumkoBO",
        "forum":'boycottpal',
        'thread:ident':identifier
    }
    r= requests.get('https://disqus.com/api/3.0/threads/details.json',params=params)
    comments=int(r.json()['response']['posts'])
    boycotted.comment_count=comments

    boycotted.save()
    return HttpResponse('Increment successful. Count is now: '+str(comments))

boycotted/templates/add_boycott.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3">
                <div class="blue lighten-4 card">
                    <div class="card-content black-text center">
                        <span class="card-title">Boycott Something</span>
                        <p class="center"><i>Please enter one boycott at a time. The more users that add the same
                            boycott, the higher the boycott can be on the Trending list or Top Boycott list!</i></p>
                        <div class="panel-body">


                            <script>
                                function report_error(error) {
                                    swal({
                                        title: "Error",
                                        text: error,
                                        type: "error",
                                        html: true
                                    });
                                }


                            </script>


                            <form method="post" action="{% url 'AddBoycott' %} " class="center">
                                {% csrf_token %}

                                {% if boycott_form.non_field_errors or boycotted_form.non_field_errors %}
                                    <script>
                                        report_error('{{ boycott_form.non_field_errors }}{{ boycotted_form.non_field_errors }}')
                                    </script>
                                {% endif %}

                                <div class="row">
                                    <div class="col s12 m10 offset-m1 fieldWrapper input-field">


                                        {% if boycotted_form.name.errors %}
                                            <script>
                                                report_error('{{ boycotted_form.name.errors }}')
                                            </script>
                                        {% endif %}




                                        <label for="{{ boycotted_form.message.name }}">Who or what are you
                                            Boycotting?</label>
                                        {{ boycotted_form.name }}


                                        <script>
                                            ac = $('#id_name');
                                            ac.addClass('autocomplete');

                                        </script>

                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col s12 m10 offset-m1 fieldWrapper input-field">
                                        {% if boycott_form.reason.errors %}
                                            <script>
                                                report_error('{{ boycott_form.reason.errors }}')
                                            </script>
                                        {% endif %}

                                        <label for="{{ boycott_form.message.reason }}">Why are you boycotting
                                            them?</label>
                                        {{ boycott_form.reason }}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col s12 m10 offset-m1 fieldWrapper input-field left">
                                        <span class="label left">Category</span>
                                        {{ boycotted_form.tag.errors }}
                                        {#                                        <label for="{{ filterForm.message.tag }}">Tag</label>#}
                                        <span id="tag">{{ boycotted_form.tag }}</span>
                                    </div>

                                </div>
                                <script>

                                    $('select').on('change', function () {
                                        if (this.value == 6) {
                                            $('#id_zip').prop('disabled', false);
                                        } else {
                                            $('#id_zip').prop('disabled', true);
                                        }
                                    })                                </script>


                                <div class="row">
                                    <div class="col s12 m10 offset-m1 fieldWrapper input-field">
                                        {% if boycotted_form.zip.errors %}
                                            <script>
                                                report_error('{{ boycotted_form.zip.errors }}')
                                            </script>
                                        {% endif %}

                                        <label for="{{ boycotted_form.message.zip }}">Zipcode</label>
                                        {{ boycotted_form.zip }}
                                        <script>$('#id_zip').prop('disabled', true);</script>
                                    </div>

                                </div>


                                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                                    <i class="material-icons right">send</i>
                                </button>
                                <a href="/" class="waves-effect waves-light red btn"><i class="material-icons right">cancel</i>Cancel</a>


                                {#                            <a href="/register" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Sign Up</a>#}


                                {#                            <a href="/register">Sign Up</a>#}
                                <input type="hidden" name="next" value="{{ next }}"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascript %}
    <script>

        var acData = {
            {% for boycott in boycotted %}
                "{{ boycott|safe }}": null,
            {% endfor %}
        };

        $(document).ready(function () {
            $(function () {
                var $auto = $('#id_name');
                $auto.autocomplete({
                    data: acData
                });
            });


        });

    </script>

{% endblock %}

boycotted/templates/edit_boycott.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3">
                <div class="blue lighten-4 card">
                    <div class="card-content black-text center">
                        <span class="card-title"><strong>Editing:</strong> {{ name }} {{ location }}</span>

                        <script>
                            function report_error(error) {
                                swal({
                                    title: "Error",
                                    text: error,
                                    type: "error",
                                    html: true
                                });
                            }
                        </script>


                        <form method="post" action="{% url 'EditBoycott' boycott_id %} " class="center">
                            {% csrf_token %}

                            {% if boycott_form.non_field_errors %}
                                <script>
                                    report_error('{{ boycott_form.non_field_errors }}')
                                </script>
                            {% endif %}


                            <div class="row">
                                <div class="col s12 m10 offset-m1 fieldWrapper input-field">
                                    {% if boycott_form.reason.errors %}
                                        <script>
                                            report_error('{{ boycott_form.reason.errors }}')
                                        </script>
                                    {% endif %}

                                    <label for="{{ boycott_form.message.reason }}">Why are you boycotting them?</label>
                                    {{ boycott_form.reason }}
                                </div>
                            </div>
                            {% if request.user.is_superuser %}
                            <div class="row">
                                <div class="col s12 m10 offset-m1 fieldWrapper input-field left">
                                    <span class="label left">Category <span class="red-text">[ADMIN ONLY]</span></span>
                                    {{ tag_form.tag.errors }}
                                    {#                                        <label for="{{ filterForm.message.tag }}">Tag</label>#}
                                    <span id="tag">{{ tag_form.tag }}</span>
                                </div>

                            </div>
                            {% endif %}
                            <div class="row center">
                                <a class="waves-effect waves-red white red-text btn-flat" onClick="confirmit()"><i
                                        class="material-icons left">delete</i> Delete Boycott</a>
                            </div>


                            <script>
                                function confirmit() {
                                    swal({
                                        title: "Are you sure you want to delete this Boycott?",
                                        type: "warning",
                                        showCancelButton: true,
                                        confirmButtonColor: "#DD6B55",
                                        confirmButtonText: "Yes, delete it!",
                                        closeOnConfirm: false
                                    }, function () {
                                        swal({
                                            title: "Canceled!",
                                            text: "Your boycott has been deleted.",
                                            type: "success"
                                        }, function () {
                                            location.href = '/boycott/delete/{{ boycott_id }}';
                                            {#                    alert({{ appt_id }});#}
                                        });
                                    });
                                }
                            </script>


                            <div class="row">

                                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                                    <i class="material-icons right">send</i>
                                </button>

                                <a href="/" class="waves-effect waves-light red btn"><i class="material-icons right">cancel</i>Cancel</a>

                            </div>


                            {#                            <a href="/register" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Sign Up</a>#}


                            {#                            <a href="/register">Sign Up</a>#}
                            <input type="hidden" name="next" value="{{ next }}"/>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascript %}

    {#<script>#}
    {#    function username() {#}
    {##}
    {#            swal("Error", "That Username is already in use.", "error");#}
    {#    }#}
    {##}
    {#</script>#}

{% endblock %}

boycotted/templates/edit_boycotted.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3">
                <div class="blue lighten-4 card">
                    <div class="card-content black-text center">
                        <span class="card-title"><strong>Editing:</strong> {{ name }} {{ location }}</span>

                        <script>
                            function report_error(error) {
                                swal({
                                    title: "Error",
                                    text: error,
                                    type: "error",
                                    html: true
                                });
                            }
                        </script>


                        <form method="post" action="{% url 'EditBoycotted' boycotted_id %} " class="center">
                            {% csrf_token %}

                            {% if boycott_form.non_field_errors %}
                                <script>
                                    report_error('{{ boycott_form.non_field_errors }}')
                                </script>
                            {% endif %}


                            <div class="row">
                                <div class="col s12 m10 offset-m1 fieldWrapper input-field left">
                                    <span class="label left">Category <span class="red-text">[ADMIN ONLY]</span></span>
                                    {{ boycotted_form.tag.errors }}
                                    {#                                        <label for="{{ filterForm.message.tag }}">Tag</label>#}
                                    <span id="tag">{{ boycotted_form.tag }}</span>
                                </div>

                            </div>




                            <div class="row">

                                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                                    <i class="material-icons right">send</i>
                                </button>

                                <a href="/" class="waves-effect waves-light red btn"><i class="material-icons right">cancel</i>Cancel</a>

                            </div>


                            {#                            <a href="/register" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Sign Up</a>#}


                            {#                            <a href="/register">Sign Up</a>#}
                            <input type="hidden" name="next" value="{{ next }}"/>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascript %}

    {#<script>#}
    {#    function username() {#}
    {##}
    {#            swal("Error", "That Username is already in use.", "error");#}
    {#    }#}
    {##}
    {#</script>#}

{% endblock %}

boycotted/templates/view_all_boycotted.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}


    <div class="section">
        <div class="container">

            <div class="row">
                <div class="col s12 m6 offset-m3 center">
                    <h4>All Polls</h4>

                    <div class="divider"></div>
                </div>
            </div>
            <div class="row">
                <div class="col s12 m8 offset-m2 center">
                    <ul class="collection white">
                        {% if all_boycotted|length == 0 %}
                            <li class="collection-item center">
                                <div>
                                    There are no Polls yet.
                                </div>
                            </li>

                        {% else %}
                            {% for boycotted in all_boycotted %}
                                <li class="collection-item">
                                    <div>
                                        <a href="/boycotted/view/{{ boycotted.id }}">{{ boycotted.name | safe }} {{ boycotted.location | safe }}
                                        {% if request.user.is_superuser %}
                                            <a
                                                    onclick="confirmit('{{ boycotted.id }}')"
                                                    class="secondary-content right"><i
                                                    class="material-icons red-text text-lighten-1">delete</i></a>
                                            <a
                                                    href="/boycotted/edit/{{ boycotted.id }}"
                                                    class="secondary-content left"><i
                                                    class="material-icons blue-text text-darken-2">edit</i></a>

                                        {% endif %}

                                    </div>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

{% block javascript %}

    <script>
        function confirmit(id) {
            swal({
                title: "Are you sure you want to delete this Person/place?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                swal({
                    title: "Canceled!",
                    text: "The Boycotted Entity has been deleted.",
                    type: "success"
                }, function () {
                    location.href = '/boycotted/delete/' + id;
                    {#                    alert({{ appt_id }});#}
                });
            });
        }
    </script>

{% endblock %}